### ISSUE TITLE
else statement?

### ISSUE THREAD

**Issue by aktxyz** [conradakunga/BlogCode#1]
I think there should be an else here ...

https://github.com/conradakunga/BlogCode/blob/1eb4d1558cd9e2504f27592a9f8d0efe09048aaf/2021-03-09%20-%20Systm.Text.Json%20Empty%20String%20Handling/NullToEmptyStringConverter.cs#L25

```
else writer.WriteStringValue(value);
```

thanks for the converter sample !

**Comment by conradakunga** [comment]
Thanks for writing!

I have updated the post
